#!/bin/sh

device_node_create()
{
	mknod /dev/$1 c `cat /sys/class/$1/$1/dev | sed "s/:/\ /g"`
}

# Setup mdev
echo "fs" > /proc/nvt_info/bootts
echo "/sbin/mdev" > /proc/sys/kernel/hotplug
modprobe mmc_na51055
modprobe vfat
mdev -s
echo 3 > /proc/sys/vm/drop_caches;free
echo "fs" > /proc/nvt_info/bootts
