#!/bin/sh

NETWORK_SETUP_SCRIPT="/etc/init.d/net_init.sh"

do_wifi_init()
{
	if [ "$NVT_SDIO_WIFI" == "NVT_SDIO_WIFI_RTK" ]; then
		/etc/init.d/BS_Net_wifiap
	elif [ "$NVT_SDIO_WIFI" == "NVT_SDIO_WIFI_BRCM" ]; then
		modprobe bcmdhd
		# TBD
	fi
}

echo "net" > /proc/nvt_info/bootts

if [ "$NVT_ETHERNET" == "NVT_ETHERNET_NONE" ] && [ "$NVT_SDIO_WIFI" == "NVT_SDIO_WIFI_NONE" ]; then
	echo "Without network"
else
	if [ "$NVT_SDIO_WIFI" != "NVT_SDIO_WIFI_NONE" ]; then
		do_wifi_init;
	fi

	if [ "$NVT_ETHERNET" != "NVT_ETHERNET_NONE" ]; then
		modprobe ntkimethmac
		ifconfig eth0 up
		# nvtsystem will generate this network setup script
		if [ -f "$NETWORK_SETUP_SCRIPT" ]; then
			$NETWORK_SETUP_SCRIPT
		else
			echo "Configuring loopback interface"
			ifconfig lo 127.0.0.1
			if [ "$NVT_DEFAULT_NETWORK_BOOT_PROTOCOL" == "NVT_DEFAULT_NETWORK_BOOT_PROTOCOL_DHCP_SERVER" ]; then
				ifconfig eth0 192.168.0.3
				udhcpd -fS /etc/udhcpd.conf &
			elif [ "$NVT_DEFAULT_NETWORK_BOOT_PROTOCOL" == "NVT_DEFAULT_NETWORK_BOOT_PROTOCOL_DHCP_CLIENT" ]; then
				udhcpc -i %s -p /var/run/udhcpc_%s.pid -T 10 -t 1 -x hostname:$(hostname) &
				echo "w4000 NVT_DEFAULT_NETWORK_BOOT_PROTOCOL_DHCP_CLIENT"
			else
				ifconfig eth0 192.168.0.3
				echo "w4000 NETWORK else"

				source /etc/init.d/mac_address
				# ifconfig eth0 down;
				# sleep 1s
				# ifconfig eth0 hw ether 00:55:7B:B5:7D:F8;
				# sleep 1s
				# ifconfig eth0 up;
				# sleep 1s
				# TEST
			fi
		fi
	fi
fi

echo "net" > /proc/nvt_info/bootts
telnetd
free